# Markdownlint configuration for bc-express
# This config allows for educational content flexibility while maintaining quality

# MD001 - Heading levels should only increment by one level at a time
MD001: false

# MD003 - Heading style
MD003:
  style: 'atx'

# MD004 - Unordered list style
MD004:
  style: 'dash'

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length
MD013: false # Disabled for educational content

# MD022 - Headings should be surrounded by blank lines
MD022: false # Disabled for flexibility in educational formatting

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true

# MD025 - Multiple top level headings in the same document
MD025: false

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: '.,;:!?'

# MD029 - Ordered list item prefix
MD029:
  style: 'ordered'

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031: false # Disabled for educational content flexibility

# MD032 - Lists should be surrounded by blank lines
MD032: false # Disabled for educational content flexibility

# MD033 - Inline HTML
MD033:
  allowed_elements:
    ['br', 'sub', 'sup', 'kbd', 'div', 'img', 'details', 'summary']

# MD034 - Bare URL used
MD034: false # Disabled temporarily for README

# MD036 - Emphasis used instead of a heading
MD036: false

# MD040 - Fenced code blocks should have a language specified
MD040: false # Disabled for educational examples

# MD041 - First line in file should be a top level heading
MD041: false

# MD045 - Images should have alternate text (alt text)
MD045: false

# MD046 - Code block style
MD046:
  style: 'fenced'

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style
MD048:
  style: 'backtick'

# MD049 - Emphasis style should be consistent
MD049:
  style: 'asterisk'

# MD050 - Strong style should be consistent
MD050:
  style: 'asterisk'
